### ISSUE TITLE
Potential Launch Flow Refactor

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/lti-shim#4]
Currently The Launch flow works like this:

1. Platform ---(Login)---> Shim ---(Login Response)---> Platform
1. Platform ---(Launch)---> Shim
1. Shim ---(Login)---> Tool ---(Login Response)---> Shim
1. Shim ---(Launch)---> Tool

I think it will be cleaner in some ways to refactor to:

1. Platform ---(Login)---> Shim ---(Login)---> Tool
1. Tool ---(Login Response)---> Shim ---(Login Response)---> Platform
1. Platform ---(Launch)---> Shim ---(Launch)---> Tool

I spoke with @ionparticle about it a bit and it has some pros (no need for the `lti_sessions` table, better shim -> tool login error handling) and some cons (need to init user info in steps harder to ensure that only cleaned info is sent).

Its not really needed now and is more minor but I do think it overall will be better to do down the road so can be considered later.

**Comment by ionparticle** [comment]
Implemented with 60a062f933b73b57e04855d354d3977e58addee3
